--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2
-- Dumped by pg_dump version 11.21

-- Started on 2026-02-20 15:13:20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 206 (class 1255 OID 1806609978)
-- Name: notify_messenger_messages(); Type: FUNCTION; Schema: public; Owner: postgreadmin
--

CREATE FUNCTION public.notify_messenger_messages() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        PERFORM pg_notify('messenger_messages', NEW.queue_name::text);
        RETURN NEW;
    END;
$$;


ALTER FUNCTION public.notify_messenger_messages() OWNER TO postgreadmin;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 196 (class 1259 OID 1806609979)
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: postgreadmin
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO postgreadmin;

--
-- TOC entry 197 (class 1259 OID 1806609986)
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgreadmin
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 198 (class 1259 OID 1806609988)
-- Name: process_failure; Type: TABLE; Schema: public; Owner: postgreadmin
--

CREATE TABLE public.process_failure (
    id bigint NOT NULL,
    process_instance_id bigint,
    step_name character varying(64),
    message_class character varying(255),
    message_payload jsonb,
    error_message text NOT NULL,
    error_trace text,
    failed_at timestamp without time zone DEFAULT now() NOT NULL,
    retryable boolean DEFAULT true NOT NULL
);


ALTER TABLE public.process_failure OWNER TO postgreadmin;

--
-- TOC entry 199 (class 1259 OID 1806609996)
-- Name: process_failure_id_seq; Type: SEQUENCE; Schema: public; Owner: postgreadmin
--

CREATE SEQUENCE public.process_failure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.process_failure_id_seq OWNER TO postgreadmin;

--
-- TOC entry 2256 (class 0 OID 0)
-- Dependencies: 199
-- Name: process_failure_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgreadmin
--

ALTER SEQUENCE public.process_failure_id_seq OWNED BY public.process_failure.id;


--
-- TOC entry 200 (class 1259 OID 1806609998)
-- Name: process_instance; Type: TABLE; Schema: public; Owner: postgreadmin
--

CREATE TABLE public.process_instance (
    id bigint NOT NULL,
    process_type character varying(64) NOT NULL,
    business_key character varying(128),
    source_job_id bigint,
    status character varying(32) NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    started_at timestamp without time zone,
    finished_at timestamp without time zone,
    last_error text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.process_instance OWNER TO postgreadmin;

--
-- TOC entry 201 (class 1259 OID 1806610007)
-- Name: process_instance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgreadmin
--

CREATE SEQUENCE public.process_instance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.process_instance_id_seq OWNER TO postgreadmin;

--
-- TOC entry 2257 (class 0 OID 0)
-- Dependencies: 201
-- Name: process_instance_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgreadmin
--

ALTER SEQUENCE public.process_instance_id_seq OWNED BY public.process_instance.id;


--
-- TOC entry 202 (class 1259 OID 1806610009)
-- Name: process_step; Type: TABLE; Schema: public; Owner: postgreadmin
--

CREATE TABLE public.process_step (
    id bigint NOT NULL,
    process_instance_id bigint NOT NULL,
    step_name character varying(64) NOT NULL,
    status character varying(32) NOT NULL,
    attempt integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 5 NOT NULL,
    locked_at timestamp without time zone,
    last_error text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    join_group character varying(64),
    finished_at timestamp without time zone
);


ALTER TABLE public.process_step OWNER TO postgreadmin;

--
-- TOC entry 203 (class 1259 OID 1806610020)
-- Name: process_step_id_seq; Type: SEQUENCE; Schema: public; Owner: postgreadmin
--

CREATE SEQUENCE public.process_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.process_step_id_seq OWNER TO postgreadmin;

--
-- TOC entry 2258 (class 0 OID 0)
-- Dependencies: 203
-- Name: process_step_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgreadmin
--

ALTER SEQUENCE public.process_step_id_seq OWNED BY public.process_step.id;


--
-- TOC entry 204 (class 1259 OID 1806610022)
-- Name: scheduled_jobs; Type: TABLE; Schema: public; Owner: postgreadmin
--

CREATE TABLE public.scheduled_jobs (
    id bigint NOT NULL,
    job_type character varying(64) NOT NULL,
    process_type character varying(64) NOT NULL,
    business_key character varying(128),
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    scheduled_at timestamp without time zone NOT NULL,
    status character varying(32) DEFAULT 'NEW'::character varying NOT NULL,
    locked_at timestamp without time zone,
    last_error text,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.scheduled_jobs OWNER TO postgreadmin;

--
-- TOC entry 205 (class 1259 OID 1806610031)
-- Name: scheduled_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgreadmin
--

CREATE SEQUENCE public.scheduled_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.scheduled_jobs_id_seq OWNER TO postgreadmin;

--
-- TOC entry 2259 (class 0 OID 0)
-- Dependencies: 205
-- Name: scheduled_jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgreadmin
--

ALTER SEQUENCE public.scheduled_jobs_id_seq OWNED BY public.scheduled_jobs.id;


--
-- TOC entry 2077 (class 2604 OID 1806610033)
-- Name: process_failure id; Type: DEFAULT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_failure ALTER COLUMN id SET DEFAULT nextval('public.process_failure_id_seq'::regclass);


--
-- TOC entry 2081 (class 2604 OID 1806610034)
-- Name: process_instance id; Type: DEFAULT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_instance ALTER COLUMN id SET DEFAULT nextval('public.process_instance_id_seq'::regclass);


--
-- TOC entry 2087 (class 2604 OID 1806610035)
-- Name: process_step id; Type: DEFAULT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_step ALTER COLUMN id SET DEFAULT nextval('public.process_step_id_seq'::regclass);


--
-- TOC entry 2091 (class 2604 OID 1806610036)
-- Name: scheduled_jobs id; Type: DEFAULT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.scheduled_jobs ALTER COLUMN id SET DEFAULT nextval('public.scheduled_jobs_id_seq'::regclass);


--
-- TOC entry 2241 (class 0 OID 1806609979)
-- Dependencies: 196
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: postgreadmin
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- TOC entry 2243 (class 0 OID 1806609988)
-- Dependencies: 198
-- Data for Name: process_failure; Type: TABLE DATA; Schema: public; Owner: postgreadmin
--

COPY public.process_failure (id, process_instance_id, step_name, message_class, message_payload, error_message, error_trace, failed_at, retryable) FROM stdin;
\.


--
-- TOC entry 2245 (class 0 OID 1806609998)
-- Dependencies: 200
-- Data for Name: process_instance; Type: TABLE DATA; Schema: public; Owner: postgreadmin
--

COPY public.process_instance (id, process_type, business_key, source_job_id, status, payload, started_at, finished_at, last_error, created_at, updated_at) FROM stdin;
86	order_fulfillment	ORDER-1003f	89	COMPLETED	{"orderId": 1003}	2026-02-20 12:10:10	2026-02-20 15:10:20.151626	\N	2026-02-20 15:10:10.481826	2026-02-20 15:10:10.481826
\.


--
-- TOC entry 2247 (class 0 OID 1806610009)
-- Dependencies: 202
-- Data for Name: process_step; Type: TABLE DATA; Schema: public; Owner: postgreadmin
--

COPY public.process_step (id, process_instance_id, step_name, status, attempt, max_attempts, locked_at, last_error, payload, created_at, updated_at, join_group, finished_at) FROM stdin;
299	86	prepare	DONE	1	5	2026-02-20 15:10:11.931997	\N	{}	2026-02-20 15:10:10.481826	2026-02-20 15:10:12.950992	\N	2026-02-20 15:10:12.950992
300	86	dispatch	DONE	1	5	2026-02-20 15:10:13.141029	\N	{}	2026-02-20 12:10:13	2026-02-20 15:10:13.15147	\N	2026-02-20 15:10:13.15147
301	86	call_api_a	DONE	1	5	2026-02-20 15:10:13.275153	\N	{}	2026-02-20 15:10:13.161738	2026-02-20 15:10:14.289743	dispatch_group	2026-02-20 15:10:14.289743
302	86	call_api_b	DONE	1	5	2026-02-20 15:10:14.379458	\N	{}	2026-02-20 15:10:13.161738	2026-02-20 15:10:15.393428	dispatch_group	2026-02-20 15:10:15.393428
303	86	generate_doc	DONE	1	5	2026-02-20 15:10:15.499741	\N	{}	2026-02-20 15:10:13.161738	2026-02-20 15:10:16.516237	dispatch_group	2026-02-20 15:10:16.516237
304	86	post_dispatch	DONE	1	5	2026-02-20 15:10:16.632438	\N	{}	2026-02-20 15:10:16.542943	2026-02-20 15:10:16.642746	\N	2026-02-20 15:10:16.642746
305	86	archive	DONE	1	5	2026-02-20 15:10:16.731273	\N	{}	2026-02-20 12:10:16	2026-02-20 15:10:16.74154	\N	2026-02-20 15:10:16.74154
306	86	archive_db	DONE	1	5	2026-02-20 15:10:16.84981	\N	{}	2026-02-20 15:10:16.751507	2026-02-20 15:10:17.863669	archive_group	2026-02-20 15:10:17.863669
307	86	archive_files	DONE	1	5	2026-02-20 15:10:17.976298	\N	{}	2026-02-20 15:10:16.751507	2026-02-20 15:10:19.001758	archive_group	2026-02-20 15:10:19.001758
308	86	finalize	DONE	1	5	2026-02-20 15:10:19.120105	\N	{}	2026-02-20 15:10:19.021792	2026-02-20 15:10:20.151626	\N	2026-02-20 15:10:20.151626
\.


--
-- TOC entry 2249 (class 0 OID 1806610022)
-- Dependencies: 204
-- Data for Name: scheduled_jobs; Type: TABLE DATA; Schema: public; Owner: postgreadmin
--

COPY public.scheduled_jobs (id, job_type, process_type, business_key, payload, scheduled_at, status, locked_at, last_error, created_at) FROM stdin;
89	START_PROCESS	order_fulfillment	ORDER-1003f	{"orderId": 1003}	2026-02-20 15:10:10.42934	DONE	2026-02-20 15:10:10.481826	\N	2026-02-20 15:10:10.42934
\.


--
-- TOC entry 2260 (class 0 OID 0)
-- Dependencies: 197
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgreadmin
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 404, true);


--
-- TOC entry 2261 (class 0 OID 0)
-- Dependencies: 199
-- Name: process_failure_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgreadmin
--

SELECT pg_catalog.setval('public.process_failure_id_seq', 1, false);


--
-- TOC entry 2262 (class 0 OID 0)
-- Dependencies: 201
-- Name: process_instance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgreadmin
--

SELECT pg_catalog.setval('public.process_instance_id_seq', 86, true);


--
-- TOC entry 2263 (class 0 OID 0)
-- Dependencies: 203
-- Name: process_step_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgreadmin
--

SELECT pg_catalog.setval('public.process_step_id_seq', 308, true);


--
-- TOC entry 2264 (class 0 OID 0)
-- Dependencies: 205
-- Name: scheduled_jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgreadmin
--

SELECT pg_catalog.setval('public.scheduled_jobs_id_seq', 89, true);


--
-- TOC entry 2094 (class 2606 OID 1806610038)
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- TOC entry 2096 (class 2606 OID 1806610040)
-- Name: process_failure process_failure_pkey; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_failure
    ADD CONSTRAINT process_failure_pkey PRIMARY KEY (id);


--
-- TOC entry 2101 (class 2606 OID 1806610042)
-- Name: process_instance process_instance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_instance
    ADD CONSTRAINT process_instance_pkey PRIMARY KEY (id);


--
-- TOC entry 2109 (class 2606 OID 1806610044)
-- Name: process_step process_step_pkey; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_step
    ADD CONSTRAINT process_step_pkey PRIMARY KEY (id);


--
-- TOC entry 2111 (class 2606 OID 1806610046)
-- Name: process_step process_step_process_instance_id_step_name_key; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_step
    ADD CONSTRAINT process_step_process_instance_id_step_name_key UNIQUE (process_instance_id, step_name);


--
-- TOC entry 2116 (class 2606 OID 1806610048)
-- Name: scheduled_jobs scheduled_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.scheduled_jobs
    ADD CONSTRAINT scheduled_jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 2103 (class 2606 OID 1806610050)
-- Name: process_instance uniq_process; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_instance
    ADD CONSTRAINT uniq_process UNIQUE (process_type, business_key);


--
-- TOC entry 2113 (class 2606 OID 1806610052)
-- Name: process_step uniq_step; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_step
    ADD CONSTRAINT uniq_step UNIQUE (process_instance_id, step_name);


--
-- TOC entry 2105 (class 2606 OID 1806610054)
-- Name: process_instance uq_process_business; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_instance
    ADD CONSTRAINT uq_process_business UNIQUE (process_type, business_key);


--
-- TOC entry 2097 (class 1259 OID 1806610055)
-- Name: idx_process_instance_business_key; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE UNIQUE INDEX idx_process_instance_business_key ON public.process_instance USING btree (process_type, business_key);


--
-- TOC entry 2098 (class 1259 OID 1806610056)
-- Name: idx_process_instance_source_job_id; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE INDEX idx_process_instance_source_job_id ON public.process_instance USING btree (source_job_id);


--
-- TOC entry 2099 (class 1259 OID 1806610057)
-- Name: idx_process_instance_type_status; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE INDEX idx_process_instance_type_status ON public.process_instance USING btree (process_type, status);


--
-- TOC entry 2106 (class 1259 OID 1806610058)
-- Name: idx_process_step_join_group; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE INDEX idx_process_step_join_group ON public.process_step USING btree (process_instance_id, join_group);


--
-- TOC entry 2107 (class 1259 OID 1806610059)
-- Name: idx_process_step_status; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE INDEX idx_process_step_status ON public.process_step USING btree (status);


--
-- TOC entry 2114 (class 1259 OID 1806610060)
-- Name: idx_scheduled_jobs_status_time; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE INDEX idx_scheduled_jobs_status_time ON public.scheduled_jobs USING btree (status, scheduled_at);


--
-- TOC entry 2092 (class 1259 OID 1806610061)
-- Name: messenger_messages_idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE INDEX messenger_messages_idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- TOC entry 2119 (class 2620 OID 1806610062)
-- Name: messenger_messages notify_trigger; Type: TRIGGER; Schema: public; Owner: postgreadmin
--

CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON public.messenger_messages FOR EACH ROW EXECUTE PROCEDURE public.notify_messenger_messages();


--
-- TOC entry 2117 (class 2606 OID 1806610063)
-- Name: process_instance fk_process_instance_source_job; Type: FK CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_instance
    ADD CONSTRAINT fk_process_instance_source_job FOREIGN KEY (source_job_id) REFERENCES public.scheduled_jobs(id);


--
-- TOC entry 2118 (class 2606 OID 1806610068)
-- Name: process_step process_step_process_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_step
    ADD CONSTRAINT process_step_process_instance_id_fkey FOREIGN KEY (process_instance_id) REFERENCES public.process_instance(id) ON DELETE CASCADE;


-- Completed on 2026-02-20 15:13:21

--
-- PostgreSQL database dump complete
--

