--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2
-- Dumped by pg_dump version 11.21

-- Started on 2026-02-04 12:10:48

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 206 (class 1255 OID 1798253439)
-- Name: notify_messenger_messages(); Type: FUNCTION; Schema: public; Owner: postgreadmin
--

CREATE FUNCTION public.notify_messenger_messages() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        PERFORM pg_notify('messenger_messages', NEW.queue_name::text);
        RETURN NEW;
    END;
$$;


ALTER FUNCTION public.notify_messenger_messages() OWNER TO postgreadmin;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 196 (class 1259 OID 1798253440)
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: postgreadmin
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO postgreadmin;

--
-- TOC entry 197 (class 1259 OID 1798253447)
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgreadmin
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 1798269438)
-- Name: process_failure; Type: TABLE; Schema: public; Owner: postgreadmin
--

CREATE TABLE public.process_failure (
    id bigint NOT NULL,
    process_instance_id bigint,
    step_name character varying(64),
    message_class character varying(255),
    message_payload jsonb,
    error_message text NOT NULL,
    error_trace text,
    failed_at timestamp without time zone DEFAULT now() NOT NULL,
    retryable boolean DEFAULT true NOT NULL
);


ALTER TABLE public.process_failure OWNER TO postgreadmin;

--
-- TOC entry 200 (class 1259 OID 1798269436)
-- Name: process_failure_id_seq; Type: SEQUENCE; Schema: public; Owner: postgreadmin
--

CREATE SEQUENCE public.process_failure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.process_failure_id_seq OWNER TO postgreadmin;

--
-- TOC entry 2251 (class 0 OID 0)
-- Dependencies: 200
-- Name: process_failure_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgreadmin
--

ALTER SEQUENCE public.process_failure_id_seq OWNED BY public.process_failure.id;


--
-- TOC entry 203 (class 1259 OID 1798652579)
-- Name: process_instance; Type: TABLE; Schema: public; Owner: postgreadmin
--

CREATE TABLE public.process_instance (
    id bigint NOT NULL,
    process_type character varying(64) NOT NULL,
    business_key character varying(128),
    source_job_id bigint,
    status character varying(32) NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    started_at timestamp without time zone,
    finished_at timestamp without time zone,
    last_error text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.process_instance OWNER TO postgreadmin;

--
-- TOC entry 202 (class 1259 OID 1798652577)
-- Name: process_instance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgreadmin
--

CREATE SEQUENCE public.process_instance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.process_instance_id_seq OWNER TO postgreadmin;

--
-- TOC entry 2252 (class 0 OID 0)
-- Dependencies: 202
-- Name: process_instance_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgreadmin
--

ALTER SEQUENCE public.process_instance_id_seq OWNED BY public.process_instance.id;


--
-- TOC entry 205 (class 1259 OID 1798653771)
-- Name: process_step; Type: TABLE; Schema: public; Owner: postgreadmin
--

CREATE TABLE public.process_step (
    id bigint NOT NULL,
    process_instance_id bigint NOT NULL,
    step_name character varying(64) NOT NULL,
    status character varying(32) NOT NULL,
    attempt integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 5 NOT NULL,
    locked_at timestamp without time zone,
    last_error text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.process_step OWNER TO postgreadmin;

--
-- TOC entry 204 (class 1259 OID 1798653769)
-- Name: process_step_id_seq; Type: SEQUENCE; Schema: public; Owner: postgreadmin
--

CREATE SEQUENCE public.process_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.process_step_id_seq OWNER TO postgreadmin;

--
-- TOC entry 2253 (class 0 OID 0)
-- Dependencies: 204
-- Name: process_step_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgreadmin
--

ALTER SEQUENCE public.process_step_id_seq OWNED BY public.process_step.id;


--
-- TOC entry 199 (class 1259 OID 1798269134)
-- Name: scheduled_jobs; Type: TABLE; Schema: public; Owner: postgreadmin
--

CREATE TABLE public.scheduled_jobs (
    id bigint NOT NULL,
    job_type character varying(64) NOT NULL,
    process_type character varying(64) NOT NULL,
    business_key character varying(128),
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    scheduled_at timestamp without time zone NOT NULL,
    status character varying(32) DEFAULT 'NEW'::character varying NOT NULL,
    locked_at timestamp without time zone,
    last_error text,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.scheduled_jobs OWNER TO postgreadmin;

--
-- TOC entry 198 (class 1259 OID 1798269132)
-- Name: scheduled_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgreadmin
--

CREATE SEQUENCE public.scheduled_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.scheduled_jobs_id_seq OWNER TO postgreadmin;

--
-- TOC entry 2254 (class 0 OID 0)
-- Dependencies: 198
-- Name: scheduled_jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgreadmin
--

ALTER SEQUENCE public.scheduled_jobs_id_seq OWNED BY public.scheduled_jobs.id;


--
-- TOC entry 2079 (class 2604 OID 1798269441)
-- Name: process_failure id; Type: DEFAULT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_failure ALTER COLUMN id SET DEFAULT nextval('public.process_failure_id_seq'::regclass);


--
-- TOC entry 2082 (class 2604 OID 1798652582)
-- Name: process_instance id; Type: DEFAULT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_instance ALTER COLUMN id SET DEFAULT nextval('public.process_instance_id_seq'::regclass);


--
-- TOC entry 2086 (class 2604 OID 1798653774)
-- Name: process_step id; Type: DEFAULT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_step ALTER COLUMN id SET DEFAULT nextval('public.process_step_id_seq'::regclass);


--
-- TOC entry 2075 (class 2604 OID 1798269137)
-- Name: scheduled_jobs id; Type: DEFAULT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.scheduled_jobs ALTER COLUMN id SET DEFAULT nextval('public.scheduled_jobs_id_seq'::regclass);


--
-- TOC entry 2236 (class 0 OID 1798253440)
-- Dependencies: 196
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: postgreadmin
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- TOC entry 2241 (class 0 OID 1798269438)
-- Dependencies: 201
-- Data for Name: process_failure; Type: TABLE DATA; Schema: public; Owner: postgreadmin
--

COPY public.process_failure (id, process_instance_id, step_name, message_class, message_payload, error_message, error_trace, failed_at, retryable) FROM stdin;
\.


--
-- TOC entry 2243 (class 0 OID 1798652579)
-- Dependencies: 203
-- Data for Name: process_instance; Type: TABLE DATA; Schema: public; Owner: postgreadmin
--

COPY public.process_instance (id, process_type, business_key, source_job_id, status, payload, started_at, finished_at, last_error, created_at, updated_at) FROM stdin;
1	order_fulfillment	ORDER-123	2	COMPLETED	{"orderId": 124}	2026-02-04 08:52:10	2026-02-04 12:04:43.846362	\N	2026-02-04 11:50:46.883161	2026-02-04 11:50:46.883161
\.


--
-- TOC entry 2245 (class 0 OID 1798653771)
-- Dependencies: 205
-- Data for Name: process_step; Type: TABLE DATA; Schema: public; Owner: postgreadmin
--

COPY public.process_step (id, process_instance_id, step_name, status, attempt, max_attempts, locked_at, last_error, payload, created_at, updated_at) FROM stdin;
1	1	prepare	DONE	1	5	\N	\N	{}	2026-02-04 11:50:46.883161	2026-02-04 11:50:46.883161
2	1	dispatch	DONE	1	5	\N	\N	{}	2026-02-04 11:57:29.846373	2026-02-04 11:57:29.846373
3	1	finalize	DONE	1	5	\N	\N	{}	2026-02-04 12:01:53.763181	2026-02-04 12:01:53.763181
\.


--
-- TOC entry 2239 (class 0 OID 1798269134)
-- Dependencies: 199
-- Data for Name: scheduled_jobs; Type: TABLE DATA; Schema: public; Owner: postgreadmin
--

COPY public.scheduled_jobs (id, job_type, process_type, business_key, payload, scheduled_at, status, locked_at, last_error, created_at) FROM stdin;
1	START_PROCESS	order_fulfillment	ORDER-123	{"orderId": 123}	2026-02-03 17:52:37.867093	DONE	2026-02-03 17:54:16.208447	\N	2026-02-03 17:52:37.867093
2	START_PROCESS	order_fulfillment	ORDER-123	{"orderId": 124}	2026-02-03 17:57:15.773897	DONE	2026-02-04 11:50:46.883161	\N	2026-02-03 17:57:15.773897
\.


--
-- TOC entry 2255 (class 0 OID 0)
-- Dependencies: 197
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgreadmin
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 45, true);


--
-- TOC entry 2256 (class 0 OID 0)
-- Dependencies: 200
-- Name: process_failure_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgreadmin
--

SELECT pg_catalog.setval('public.process_failure_id_seq', 1, false);


--
-- TOC entry 2257 (class 0 OID 0)
-- Dependencies: 202
-- Name: process_instance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgreadmin
--

SELECT pg_catalog.setval('public.process_instance_id_seq', 1, true);


--
-- TOC entry 2258 (class 0 OID 0)
-- Dependencies: 204
-- Name: process_step_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgreadmin
--

SELECT pg_catalog.setval('public.process_step_id_seq', 3, true);


--
-- TOC entry 2259 (class 0 OID 0)
-- Dependencies: 198
-- Name: scheduled_jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgreadmin
--

SELECT pg_catalog.setval('public.scheduled_jobs_id_seq', 2, true);


--
-- TOC entry 2094 (class 2606 OID 1798253487)
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- TOC entry 2099 (class 2606 OID 1798269448)
-- Name: process_failure process_failure_pkey; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_failure
    ADD CONSTRAINT process_failure_pkey PRIMARY KEY (id);


--
-- TOC entry 2104 (class 2606 OID 1798652590)
-- Name: process_instance process_instance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_instance
    ADD CONSTRAINT process_instance_pkey PRIMARY KEY (id);


--
-- TOC entry 2109 (class 2606 OID 1798653784)
-- Name: process_step process_step_pkey; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_step
    ADD CONSTRAINT process_step_pkey PRIMARY KEY (id);


--
-- TOC entry 2111 (class 2606 OID 1798653786)
-- Name: process_step process_step_process_instance_id_step_name_key; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_step
    ADD CONSTRAINT process_step_process_instance_id_step_name_key UNIQUE (process_instance_id, step_name);


--
-- TOC entry 2097 (class 2606 OID 1798269145)
-- Name: scheduled_jobs scheduled_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.scheduled_jobs
    ADD CONSTRAINT scheduled_jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 2106 (class 2606 OID 1798652592)
-- Name: process_instance uq_process_business; Type: CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_instance
    ADD CONSTRAINT uq_process_business UNIQUE (process_type, business_key);


--
-- TOC entry 2100 (class 1259 OID 1798653340)
-- Name: idx_process_instance_business_key; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE UNIQUE INDEX idx_process_instance_business_key ON public.process_instance USING btree (process_type, business_key);


--
-- TOC entry 2101 (class 1259 OID 1798668548)
-- Name: idx_process_instance_source_job_id; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE INDEX idx_process_instance_source_job_id ON public.process_instance USING btree (source_job_id);


--
-- TOC entry 2102 (class 1259 OID 1798653339)
-- Name: idx_process_instance_type_status; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE INDEX idx_process_instance_type_status ON public.process_instance USING btree (process_type, status);


--
-- TOC entry 2107 (class 1259 OID 1798653792)
-- Name: idx_process_step_status; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE INDEX idx_process_step_status ON public.process_step USING btree (status);


--
-- TOC entry 2095 (class 1259 OID 1798269146)
-- Name: idx_scheduled_jobs_status_time; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE INDEX idx_scheduled_jobs_status_time ON public.scheduled_jobs USING btree (status, scheduled_at);


--
-- TOC entry 2092 (class 1259 OID 1798253504)
-- Name: messenger_messages_idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: postgreadmin
--

CREATE INDEX messenger_messages_idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- TOC entry 2114 (class 2620 OID 1798253505)
-- Name: messenger_messages notify_trigger; Type: TRIGGER; Schema: public; Owner: postgreadmin
--

CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON public.messenger_messages FOR EACH ROW EXECUTE PROCEDURE public.notify_messenger_messages();


--
-- TOC entry 2112 (class 2606 OID 1798669039)
-- Name: process_instance fk_process_instance_source_job; Type: FK CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_instance
    ADD CONSTRAINT fk_process_instance_source_job FOREIGN KEY (source_job_id) REFERENCES public.scheduled_jobs(id);


--
-- TOC entry 2113 (class 2606 OID 1798653787)
-- Name: process_step process_step_process_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgreadmin
--

ALTER TABLE ONLY public.process_step
    ADD CONSTRAINT process_step_process_instance_id_fkey FOREIGN KEY (process_instance_id) REFERENCES public.process_instance(id) ON DELETE CASCADE;


-- Completed on 2026-02-04 12:10:48

--
-- PostgreSQL database dump complete
--

